#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("Cab360Driver.Resource", IsApplication=true)]

namespace Cab360Driver
{
	
	
	[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Animation
		{
			
			// aapt resource value: 0x7F010000
			public const int enter = 2130771968;
			
			// aapt resource value: 0x7F010001
			public const int error_frame_in = 2130771969;
			
			// aapt resource value: 0x7F010002
			public const int error_x_in = 2130771970;
			
			// aapt resource value: 0x7F010003
			public const int exit = 2130771971;
			
			// aapt resource value: 0x7F010004
			public const int modal_in = 2130771972;
			
			// aapt resource value: 0x7F010005
			public const int modal_out = 2130771973;
			
			// aapt resource value: 0x7F010006
			public const int pop_enter = 2130771974;
			
			// aapt resource value: 0x7F010007
			public const int pop_exit = 2130771975;
			
			// aapt resource value: 0x7F010008
			public const int slide_in_right = 2130771976;
			
			// aapt resource value: 0x7F010009
			public const int slide_out_left = 2130771977;
			
			// aapt resource value: 0x7F01000A
			public const int success_bow_roate = 2130771978;
			
			// aapt resource value: 0x7F01000B
			public const int success_mask_layout = 2130771979;
			
			static Animation()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Animation()
			{
			}
		}
		
		public partial class Animator
		{
			
			// aapt resource value: 0x7F020000
			public const int lift_on_touch = 2130837504;
			
			static Animator()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Animator()
			{
			}
		}
		
		public partial class Attribute
		{
			
			// aapt resource value: 0x7F030000
			public const int card_end_icon = 2130903040;
			
			// aapt resource value: 0x7F030001
			public const int card_text_body = 2130903041;
			
			// aapt resource value: 0x7F030002
			public const int card_text_head = 2130903042;
			
			// aapt resource value: 0x7F030003
			public const int fromDeg = 2130903043;
			
			// aapt resource value: 0x7F030004
			public const int matProg_barColor = 2130903044;
			
			// aapt resource value: 0x7F030005
			public const int matProg_barSpinCycleTime = 2130903045;
			
			// aapt resource value: 0x7F030006
			public const int matProg_barWidth = 2130903046;
			
			// aapt resource value: 0x7F030007
			public const int matProg_circleRadius = 2130903047;
			
			// aapt resource value: 0x7F030008
			public const int matProg_fillRadius = 2130903048;
			
			// aapt resource value: 0x7F030009
			public const int matProg_linearProgress = 2130903049;
			
			// aapt resource value: 0x7F03000A
			public const int matProg_progressIndeterminate = 2130903050;
			
			// aapt resource value: 0x7F03000B
			public const int matProg_rimColor = 2130903051;
			
			// aapt resource value: 0x7F03000C
			public const int matProg_rimWidth = 2130903052;
			
			// aapt resource value: 0x7F03000D
			public const int matProg_spinSpeed = 2130903053;
			
			// aapt resource value: 0x7F03000E
			public const int pivotX = 2130903054;
			
			// aapt resource value: 0x7F03000F
			public const int pivotY = 2130903055;
			
			// aapt resource value: 0x7F030010
			public const int rollType = 2130903056;
			
			// aapt resource value: 0x7F030011
			public const int toDeg = 2130903057;
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7F040000
			public const int blue_btn_bg_color = 2130968576;
			
			// aapt resource value: 0x7F040001
			public const int blue_btn_bg_pressed_color = 2130968577;
			
			// aapt resource value: 0x7F040002
			public const int button_text_color = 2130968578;
			
			// aapt resource value: 0x7F040003
			public const int colorAccent = 2130968579;
			
			// aapt resource value: 0x7F040004
			public const int colorAccentLight = 2130968580;
			
			// aapt resource value: 0x7F040005
			public const int colorCardTint = 2130968581;
			
			// aapt resource value: 0x7F040006
			public const int colorDisabled = 2130968582;
			
			// aapt resource value: 0x7F040007
			public const int colorIvory = 2130968583;
			
			// aapt resource value: 0x7F040008
			public const int colorPrimary = 2130968584;
			
			// aapt resource value: 0x7F040009
			public const int colorPrimaryDark = 2130968585;
			
			// aapt resource value: 0x7F04000A
			public const int colorTransparent = 2130968586;
			
			// aapt resource value: 0x7F04000B
			public const int colorTransparentWhite_30 = 2130968587;
			
			// aapt resource value: 0x7F04000C
			public const int colorTransparentWhite_35 = 2130968588;
			
			// aapt resource value: 0x7F04000D
			public const int colorTransparentWhite_40 = 2130968589;
			
			// aapt resource value: 0x7F04000E
			public const int colorTransparentWhite_45 = 2130968590;
			
			// aapt resource value: 0x7F04000F
			public const int colorTransparentWhite_50 = 2130968591;
			
			// aapt resource value: 0x7F040010
			public const int colorTransparentWhite_55 = 2130968592;
			
			// aapt resource value: 0x7F040011
			public const int colorTransparentWhite_60 = 2130968593;
			
			// aapt resource value: 0x7F040012
			public const int colorTransparentWhite_65 = 2130968594;
			
			// aapt resource value: 0x7F040013
			public const int colorTransparentWhite_70 = 2130968595;
			
			// aapt resource value: 0x7F040014
			public const int colorTransparentWhite_75 = 2130968596;
			
			// aapt resource value: 0x7F040015
			public const int colorTransparentWhite_80 = 2130968597;
			
			// aapt resource value: 0x7F040016
			public const int colorTransparentWhite_85 = 2130968598;
			
			// aapt resource value: 0x7F040017
			public const int colorTransparentWhite_90 = 2130968599;
			
			// aapt resource value: 0x7F040018
			public const int colorTransparentWhite_95 = 2130968600;
			
			// aapt resource value: 0x7F040019
			public const int error_stroke_color = 2130968601;
			
			// aapt resource value: 0x7F04001A
			public const int facebookPrimary = 2130968602;
			
			// aapt resource value: 0x7F04001B
			public const int float_transparent = 2130968603;
			
			// aapt resource value: 0x7F04001C
			public const int gray_btn_bg_color = 2130968604;
			
			// aapt resource value: 0x7F04001D
			public const int gray_btn_bg_pressed_color = 2130968605;
			
			// aapt resource value: 0x7F04001E
			public const int ic_launcher_background = 2130968606;
			
			// aapt resource value: 0x7F04001F
			public const int material_blue_grey_80 = 2130968607;
			
			// aapt resource value: 0x7F040020
			public const int material_blue_grey_90 = 2130968608;
			
			// aapt resource value: 0x7F040021
			public const int material_blue_grey_95 = 2130968609;
			
			// aapt resource value: 0x7F040022
			public const int material_deep_teal_20 = 2130968610;
			
			// aapt resource value: 0x7F040023
			public const int material_deep_teal_50 = 2130968611;
			
			// aapt resource value: 0x7F040024
			public const int red_btn_bg_color = 2130968612;
			
			// aapt resource value: 0x7F040025
			public const int red_btn_bg_pressed_color = 2130968613;
			
			// aapt resource value: 0x7F040026
			public const int success_stroke_color = 2130968614;
			
			// aapt resource value: 0x7F040027
			public const int sweet_dialog_bg_color = 2130968615;
			
			// aapt resource value: 0x7F040028
			public const int text_color = 2130968616;
			
			// aapt resource value: 0x7F040029
			public const int trans_success_stroke_color = 2130968617;
			
			// aapt resource value: 0x7F04002A
			public const int warning_stroke_color = 2130968618;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Dimension
		{
			
			// aapt resource value: 0x7F050000
			public const int alert_width = 2131034112;
			
			// aapt resource value: 0x7F050001
			public const int app_bar_height = 2131034113;
			
			// aapt resource value: 0x7F050002
			public const int bottom_sheet_corner_radius = 2131034114;
			
			// aapt resource value: 0x7F050003
			public const int bottom_sheet_top_padding = 2131034115;
			
			// aapt resource value: 0x7F050004
			public const int circular_radius = 2131034116;
			
			// aapt resource value: 0x7F050005
			public const int common_circle_width = 2131034117;
			
			// aapt resource value: 0x7F050006
			public const int fab_margin = 2131034118;
			
			// aapt resource value: 0x7F050007
			public const int headerTextSize = 2131034119;
			
			// aapt resource value: 0x7F050008
			public const int image_final_width = 2131034120;
			
			// aapt resource value: 0x7F050009
			public const int image_width = 2131034121;
			
			// aapt resource value: 0x7F05000A
			public const int margin_bottom = 2131034122;
			
			// aapt resource value: 0x7F05000B
			public const int marrgin_start_end = 2131034123;
			
			// aapt resource value: 0x7F05000C
			public const int progress_circle_radius = 2131034124;
			
			// aapt resource value: 0x7F05000D
			public const int spacing_normal = 2131034125;
			
			// aapt resource value: 0x7F05000E
			public const int text_margin = 2131034126;
			
			static Dimension()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Dimension()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7F060000
			public const int bg_bottomsheet_dg = 2131099648;
			
			// aapt resource value: 0x7F060001
			public const int blue_button_background = 2131099649;
			
			// aapt resource value: 0x7F060002
			public const int border_bg = 2131099650;
			
			// aapt resource value: 0x7F060003
			public const int bottomnav_iconstate_list = 2131099651;
			
			// aapt resource value: 0x7F060004
			public const int boy_new = 2131099652;
			
			// aapt resource value: 0x7F060005
			public const int btn_background = 2131099653;
			
			// aapt resource value: 0x7F060006
			public const int btn_txt_clr_tggl = 2131099654;
			
			// aapt resource value: 0x7F060007
			public const int cardview_focus_bg_tggl = 2131099655;
			
			// aapt resource value: 0x7F060008
			public const int circle = 2131099656;
			
			// aapt resource value: 0x7F06000B
			public const int circleyellowfil = 2131099659;
			
			// aapt resource value: 0x7F060009
			public const int circle_border = 2131099657;
			
			// aapt resource value: 0x7F06000A
			public const int circle_border_outline = 2131099658;
			
			// aapt resource value: 0x7F06000D
			public const int circularbordersolid = 2131099661;
			
			// aapt resource value: 0x7F06000C
			public const int circular_grey_bordersolid = 2131099660;
			
			// aapt resource value: 0x7F06000E
			public const int dialog_background = 2131099662;
			
			// aapt resource value: 0x7F06000F
			public const int divider = 2131099663;
			
			// aapt resource value: 0x7F060010
			public const int driver_2 = 2131099664;
			
			// aapt resource value: 0x7F060011
			public const int error_center_x = 2131099665;
			
			// aapt resource value: 0x7F060012
			public const int error_circle = 2131099666;
			
			// aapt resource value: 0x7F060013
			public const int grad = 2131099667;
			
			// aapt resource value: 0x7F060014
			public const int gray_button_background = 2131099668;
			
			// aapt resource value: 0x7F060015
			public const int greenball = 2131099669;
			
			// aapt resource value: 0x7F060016
			public const int ic_account_plchldr = 2131099670;
			
			// aapt resource value: 0x7F060017
			public const int ic_bell = 2131099671;
			
			// aapt resource value: 0x7F060018
			public const int ic_bg = 2131099672;
			
			// aapt resource value: 0x7F060019
			public const int ic_call = 2131099673;
			
			// aapt resource value: 0x7F06001A
			public const int ic_cancel = 2131099674;
			
			// aapt resource value: 0x7F06001B
			public const int ic_car_offline = 2131099675;
			
			// aapt resource value: 0x7F06001C
			public const int ic_car_online = 2131099676;
			
			// aapt resource value: 0x7F06001D
			public const int ic_distance = 2131099677;
			
			// aapt resource value: 0x7F06001E
			public const int ic_driver1 = 2131099678;
			
			// aapt resource value: 0x7F06001F
			public const int ic_driver2 = 2131099679;
			
			// aapt resource value: 0x7F060020
			public const int ic_duration = 2131099680;
			
			// aapt resource value: 0x7F060021
			public const int ic_error = 2131099681;
			
			// aapt resource value: 0x7F060022
			public const int ic_home = 2131099682;
			
			// aapt resource value: 0x7F060023
			public const int ic_launcher_foreground = 2131099683;
			
			// aapt resource value: 0x7F060024
			public const int ic_location = 2131099684;
			
			// aapt resource value: 0x7F060025
			public const int ic_money = 2131099685;
			
			// aapt resource value: 0x7F060026
			public const int ic_navigate = 2131099686;
			
			// aapt resource value: 0x7F060027
			public const int ic_navigation = 2131099687;
			
			// aapt resource value: 0x7F060028
			public const int ic_next = 2131099688;
			
			// aapt resource value: 0x7F060029
			public const int ic_person = 2131099689;
			
			// aapt resource value: 0x7F06002A
			public const int ic_pin = 2131099690;
			
			// aapt resource value: 0x7F06002B
			public const int ic_review1 = 2131099691;
			
			// aapt resource value: 0x7F06002C
			public const int ic_star = 2131099692;
			
			// aapt resource value: 0x7F06002D
			public const int ic_star_small = 2131099693;
			
			// aapt resource value: 0x7F06002E
			public const int ic_user = 2131099694;
			
			// aapt resource value: 0x7F06002F
			public const int menu = 2131099695;
			
			// aapt resource value: 0x7F060030
			public const int outline_btn_bg = 2131099696;
			
			// aapt resource value: 0x7F060031
			public const int partner_radio_border = 2131099697;
			
			// aapt resource value: 0x7F060032
			public const int partner_radio_end = 2131099698;
			
			// aapt resource value: 0x7F060033
			public const int partner_radio_start = 2131099699;
			
			// aapt resource value: 0x7F060034
			public const int position = 2131099700;
			
			// aapt resource value: 0x7F060035
			public const int primary_btn_bg = 2131099701;
			
			// aapt resource value: 0x7F060036
			public const int radial_frame_bg = 2131099702;
			
			// aapt resource value: 0x7F060037
			public const int radio_selector = 2131099703;
			
			// aapt resource value: 0x7F060038
			public const int radio_selector_end = 2131099704;
			
			// aapt resource value: 0x7F060039
			public const int radio_selector_start = 2131099705;
			
			// aapt resource value: 0x7F06003A
			public const int radio_txt_selector = 2131099706;
			
			// aapt resource value: 0x7F06003C
			public const int redball = 2131099708;
			
			// aapt resource value: 0x7F06003B
			public const int red_button_background = 2131099707;
			
			// aapt resource value: 0x7F06003D
			public const int secondary_btn_bg = 2131099709;
			
			// aapt resource value: 0x7F06003E
			public const int star = 2131099710;
			
			// aapt resource value: 0x7F06003F
			public const int success_bow = 2131099711;
			
			// aapt resource value: 0x7F060040
			public const int success_circle = 2131099712;
			
			// aapt resource value: 0x7F060041
			public const int taxi = 2131099713;
			
			// aapt resource value: 0x7F060042
			public const int temperature_background = 2131099714;
			
			// aapt resource value: 0x7F060043
			public const int tickcircle = 2131099715;
			
			// aapt resource value: 0x7F060044
			public const int tickinsidecircle = 2131099716;
			
			// aapt resource value: 0x7F060045
			public const int warning_circle = 2131099717;
			
			// aapt resource value: 0x7F060046
			public const int warning_sigh = 2131099718;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7F070000
			public const int accept_ride_btn = 2131165184;
			
			// aapt resource value: 0x7F070001
			public const int action_account = 2131165185;
			
			// aapt resource value: 0x7F070002
			public const int action_earning = 2131165186;
			
			// aapt resource value: 0x7F070003
			public const int action_empty = 2131165187;
			
			// aapt resource value: 0x7F070004
			public const int action_home = 2131165188;
			
			// aapt resource value: 0x7F070005
			public const int action_rating = 2131165189;
			
			// aapt resource value: 0x7F070006
			public const int action_settings = 2131165190;
			
			// aapt resource value: 0x7F070007
			public const int autocity_et = 2131165191;
			
			// aapt resource value: 0x7F070008
			public const int back_btn = 2131165192;
			
			// aapt resource value: 0x7F070009
			public const int bnve = 2131165193;
			
			// aapt resource value: 0x7F07000A
			public const int brand_ac_tv = 2131165194;
			
			// aapt resource value: 0x7F07000B
			public const int brand_lay = 2131165195;
			
			// aapt resource value: 0x7F07000C
			public const int btn_forgot_pass = 2131165196;
			
			// aapt resource value: 0x7F07000D
			public const int callRiderButton = 2131165197;
			
			// aapt resource value: 0x7F07000E
			public const int cancelTripButton = 2131165198;
			
			// aapt resource value: 0x7F07000F
			public const int cancel_button = 2131165199;
			
			// aapt resource value: 0x7F070010
			public const int centerMarker = 2131165200;
			
			// aapt resource value: 0x7F070011
			public const int chart_type_spinner = 2131165201;
			
			// aapt resource value: 0x7F070012
			public const int chk_fire = 2131165202;
			
			// aapt resource value: 0x7F070013
			public const int chk_insur = 2131165203;
			
			// aapt resource value: 0x7F070014
			public const int chk_inte = 2131165204;
			
			// aapt resource value: 0x7F070015
			public const int chk_road = 2131165205;
			
			// aapt resource value: 0x7F070016
			public const int collectPayButton = 2131165206;
			
			// aapt resource value: 0x7F070017
			public const int color_ac_tv = 2131165207;
			
			// aapt resource value: 0x7F070018
			public const int color_lay = 2131165208;
			
			// aapt resource value: 0x7F070019
			public const int confirm_button = 2131165209;
			
			// aapt resource value: 0x7F07001B
			public const int content_text = 2131165211;
			
			// aapt resource value: 0x7F07001A
			public const int cont_lin1 = 2131165210;
			
			// aapt resource value: 0x7F07001C
			public const int curr_user_til = 2131165212;
			
			// aapt resource value: 0x7F07001D
			public const int custom_image = 2131165213;
			
			// aapt resource value: 0x7F07001E
			public const int decline_ride_fab = 2131165214;
			
			// aapt resource value: 0x7F07001F
			public const int descConstraint = 2131165215;
			
			// aapt resource value: 0x7F070020
			public const int distance_txt = 2131165216;
			
			// aapt resource value: 0x7F070021
			public const int driver_onboarding_root = 2131165217;
			
			// aapt resource value: 0x7F070022
			public const int driver_partner_root = 2131165218;
			
			// aapt resource value: 0x7F070023
			public const int drv_capt_appbar = 2131165219;
			
			// aapt resource value: 0x7F070024
			public const int drv_capt_head_tv = 2131165220;
			
			// aapt resource value: 0x7F070025
			public const int drv_capt_l2 = 2131165221;
			
			// aapt resource value: 0x7F070026
			public const int drv_capt_req_tv = 2131165222;
			
			// aapt resource value: 0x7F070027
			public const int drv_capt_toolbar = 2131165223;
			
			// aapt resource value: 0x7F070028
			public const int drv_capt_welc_tv = 2131165224;
			
			// aapt resource value: 0x7F070029
			public const int drv_part_cnt_btn = 2131165225;
			
			// aapt resource value: 0x7F07002A
			public const int drv_part_cv1 = 2131165226;
			
			// aapt resource value: 0x7F07002B
			public const int drv_part_img_swtchr1 = 2131165227;
			
			// aapt resource value: 0x7F07002C
			public const int drv_part_intro_txt = 2131165228;
			
			// aapt resource value: 0x7F07002D
			public const int drv_part_tggl_grp = 2131165229;
			
			// aapt resource value: 0x7F07002E
			public const int drv_part_txt_swtchr1 = 2131165230;
			
			// aapt resource value: 0x7F07002F
			public const int drv_photo_txt = 2131165231;
			
			// aapt resource value: 0x7F070030
			public const int drv_photo_txt2 = 2131165232;
			
			// aapt resource value: 0x7F070031
			public const int drv_photo_txt3 = 2131165233;
			
			// aapt resource value: 0x7F070032
			public const int drv_signin_email_et = 2131165234;
			
			// aapt resource value: 0x7F070033
			public const int drv_signin_pass_et = 2131165235;
			
			// aapt resource value: 0x7F070034
			public const int drv_signin_root = 2131165236;
			
			// aapt resource value: 0x7F070035
			public const int drv_signup_city_et = 2131165237;
			
			// aapt resource value: 0x7F070036
			public const int drv_signup_code_et = 2131165238;
			
			// aapt resource value: 0x7F070037
			public const int drv_signup_code_et1 = 2131165239;
			
			// aapt resource value: 0x7F070038
			public const int drv_signup_email_et = 2131165240;
			
			// aapt resource value: 0x7F070039
			public const int drv_signup_fname_et = 2131165241;
			
			// aapt resource value: 0x7F07003A
			public const int drv_signup_fname_et1 = 2131165242;
			
			// aapt resource value: 0x7F07003B
			public const int drv_signup_lname_et = 2131165243;
			
			// aapt resource value: 0x7F07003C
			public const int drv_signup_lname_et1 = 2131165244;
			
			// aapt resource value: 0x7F07003D
			public const int drv_signup_pass_et = 2131165245;
			
			// aapt resource value: 0x7F07003E
			public const int drv_signup_phone_et = 2131165246;
			
			// aapt resource value: 0x7F07003F
			public const int drv_signup_root = 2131165247;
			
			// aapt resource value: 0x7F070040
			public const int drv_signup_sbmtbtn = 2131165248;
			
			// aapt resource value: 0x7F070041
			public const int drv_tggl_driver_btn = 2131165249;
			
			// aapt resource value: 0x7F070042
			public const int drv_tggl_partner_btn = 2131165250;
			
			// aapt resource value: 0x7F070043
			public const int duration_txt = 2131165251;
			
			// aapt resource value: 0x7F070052
			public const int earnings_root = 2131165266;
			
			// aapt resource value: 0x7F070044
			public const int earn_amt_hd = 2131165252;
			
			// aapt resource value: 0x7F070045
			public const int earn_base_hd = 2131165253;
			
			// aapt resource value: 0x7F070046
			public const int earn_chartview = 2131165254;
			
			// aapt resource value: 0x7F070047
			public const int earn_dist_hd = 2131165255;
			
			// aapt resource value: 0x7F070048
			public const int earn_separator = 2131165256;
			
			// aapt resource value: 0x7F070049
			public const int earn_tax_txt = 2131165257;
			
			// aapt resource value: 0x7F07004A
			public const int earn_tot_dis_txt = 2131165258;
			
			// aapt resource value: 0x7F07004B
			public const int earn_tot_trip_hd = 2131165259;
			
			// aapt resource value: 0x7F07004C
			public const int earn_tot_trip_txt = 2131165260;
			
			// aapt resource value: 0x7F07004D
			public const int earn_trip_hd = 2131165261;
			
			// aapt resource value: 0x7F07004E
			public const int earn_trip_txt = 2131165262;
			
			// aapt resource value: 0x7F07004F
			public const int earn_tv1 = 2131165263;
			
			// aapt resource value: 0x7F070050
			public const int earn_tv2 = 2131165264;
			
			// aapt resource value: 0x7F070051
			public const int earn_withdraw_btn = 2131165265;
			
			// aapt resource value: 0x7F070053
			public const int error_frame = 2131165267;
			
			// aapt resource value: 0x7F070054
			public const int error_x = 2131165268;
			
			// aapt resource value: 0x7F070055
			public const int fab1 = 2131165269;
			
			// aapt resource value: 0x7F070056
			public const int fab_toggle_online = 2131165270;
			
			// aapt resource value: 0x7F070057
			public const int five_star_progress = 2131165271;
			
			// aapt resource value: 0x7F070058
			public const int four_star_progress = 2131165272;
			
			// aapt resource value: 0x7F070059
			public const int frameLayout_online = 2131165273;
			
			// aapt resource value: 0x7F07005A
			public const int from_txt = 2131165274;
			
			// aapt resource value: 0x7F07005B
			public const int greenball = 2131165275;
			
			// aapt resource value: 0x7F07005C
			public const int intro_takelicense_btn1 = 2131165276;
			
			// aapt resource value: 0x7F07005D
			public const int intro_takephoto_btn = 2131165277;
			
			// aapt resource value: 0x7F07005E
			public const int license_prev_iv = 2131165278;
			
			// aapt resource value: 0x7F07005F
			public const int linear_home1 = 2131165279;
			
			// aapt resource value: 0x7F070060
			public const int loader = 2131165280;
			
			// aapt resource value: 0x7F070061
			public const int loading = 2131165281;
			
			// aapt resource value: 0x7F070062
			public const int main_appbar = 2131165282;
			
			// aapt resource value: 0x7F070063
			public const int main_toolbar = 2131165283;
			
			// aapt resource value: 0x7F070064
			public const int map = 2131165284;
			
			// aapt resource value: 0x7F070065
			public const int mask_left = 2131165285;
			
			// aapt resource value: 0x7F070066
			public const int mask_right = 2131165286;
			
			// aapt resource value: 0x7F070067
			public const int menu_settings = 2131165287;
			
			// aapt resource value: 0x7F070068
			public const int model_ac_tv = 2131165288;
			
			// aapt resource value: 0x7F070069
			public const int model_lay = 2131165289;
			
			// aapt resource value: 0x7F07006A
			public const int nameConstraint = 2131165290;
			
			// aapt resource value: 0x7F07006B
			public const int navigateButton = 2131165291;
			
			// aapt resource value: 0x7F07006C
			public const int no_recents_tv1 = 2131165292;
			
			// aapt resource value: 0x7F07006D
			public const int nre_linear = 2131165293;
			
			// aapt resource value: 0x7F07006E
			public const int nxt_img1 = 2131165294;
			
			// aapt resource value: 0x7F07006F
			public const int nxt_img2 = 2131165295;
			
			// aapt resource value: 0x7F070070
			public const int nxt_img3 = 2131165296;
			
			// aapt resource value: 0x7F070071
			public const int oboarding_gif = 2131165297;
			
			// aapt resource value: 0x7F070072
			public const int onbd_signin_btn = 2131165298;
			
			// aapt resource value: 0x7F070073
			public const int onbd_signup_btn = 2131165299;
			
			// aapt resource value: 0x7F070074
			public const int onbd_welcome_txt = 2131165300;
			
			// aapt resource value: 0x7F070075
			public const int one_star_proogress = 2131165301;
			
			// aapt resource value: 0x7F070076
			public const int part_cont_btn = 2131165302;
			
			// aapt resource value: 0x7F070077
			public const int part_grid1 = 2131165303;
			
			// aapt resource value: 0x7F070078
			public const int part_vehi_intro_txt = 2131165304;
			
			// aapt resource value: 0x7F070079
			public const int pls_tick_tv = 2131165305;
			
			// aapt resource value: 0x7F07007C
			public const int preview_iv = 2131165308;
			
			// aapt resource value: 0x7F07007D
			public const int preview_iv1 = 2131165309;
			
			// aapt resource value: 0x7F07007A
			public const int prev_retake_btn = 2131165306;
			
			// aapt resource value: 0x7F07007B
			public const int prev_save_btn = 2131165307;
			
			// aapt resource value: 0x7F07007E
			public const int prog1 = 2131165310;
			
			// aapt resource value: 0x7F07007F
			public const int progressWheel = 2131165311;
			
			// aapt resource value: 0x7F070080
			public const int progress_dialog = 2131165312;
			
			// aapt resource value: 0x7F070081
			public const int progress_status = 2131165313;
			
			// aapt resource value: 0x7F070082
			public const int rater_duration_tv = 2131165314;
			
			// aapt resource value: 0x7F070083
			public const int rater_name_tv1 = 2131165315;
			
			// aapt resource value: 0x7F070084
			public const int rater_profile_iv1 = 2131165316;
			
			// aapt resource value: 0x7F070085
			public const int rater_rating_tv1 = 2131165317;
			
			// aapt resource value: 0x7F070086
			public const int ratings_desc_tv = 2131165318;
			
			// aapt resource value: 0x7F070087
			public const int ratings_root = 2131165319;
			
			// aapt resource value: 0x7F070088
			public const int ratings_table1 = 2131165320;
			
			// aapt resource value: 0x7F070089
			public const int ratings_tv = 2131165321;
			
			// aapt resource value: 0x7F07008A
			public const int rec_text = 2131165322;
			
			// aapt resource value: 0x7F07008B
			public const int rec_text2 = 2131165323;
			
			// aapt resource value: 0x7F07008C
			public const int rec_text3 = 2131165324;
			
			// aapt resource value: 0x7F07008D
			public const int redball = 2131165325;
			
			// aapt resource value: 0x7F07008E
			public const int reg_no_til = 2131165326;
			
			// aapt resource value: 0x7F07008F
			public const int reg_viewpager1 = 2131165327;
			
			// aapt resource value: 0x7F070090
			public const int req_c1 = 2131165328;
			
			// aapt resource value: 0x7F070091
			public const int req_c2 = 2131165329;
			
			// aapt resource value: 0x7F070092
			public const int req_c3 = 2131165330;
			
			// aapt resource value: 0x7F070093
			public const int review_dummy_iv1 = 2131165331;
			
			// aapt resource value: 0x7F070095
			public const int riderNameText = 2131165333;
			
			// aapt resource value: 0x7F070096
			public const int rider_details_tv = 2131165334;
			
			// aapt resource value: 0x7F070097
			public const int rider_iv = 2131165335;
			
			// aapt resource value: 0x7F070094
			public const int ride_req_ovly = 2131165332;
			
			// aapt resource value: 0x7F070098
			public const int separator = 2131165336;
			
			// aapt resource value: 0x7F070099
			public const int separator2 = 2131165337;
			
			// aapt resource value: 0x7F07009A
			public const int separator3 = 2131165338;
			
			// aapt resource value: 0x7F07009B
			public const int sign_appbar = 2131165339;
			
			// aapt resource value: 0x7F07009C
			public const int star_five_tv = 2131165340;
			
			// aapt resource value: 0x7F07009D
			public const int star_four_tv = 2131165341;
			
			// aapt resource value: 0x7F07009E
			public const int star_one_tv = 2131165342;
			
			// aapt resource value: 0x7F07009F
			public const int star_three_tv = 2131165343;
			
			// aapt resource value: 0x7F0700A0
			public const int star_two_tv = 2131165344;
			
			// aapt resource value: 0x7F0700A1
			public const int state_ac_tv = 2131165345;
			
			// aapt resource value: 0x7F0700A2
			public const int state_lay = 2131165346;
			
			// aapt resource value: 0x7F0700A3
			public const int success_frame = 2131165347;
			
			// aapt resource value: 0x7F0700A4
			public const int success_tick = 2131165348;
			
			// aapt resource value: 0x7F0700A5
			public const int summ_txt = 2131165349;
			
			// aapt resource value: 0x7F0700A6
			public const int take_ya_flp_txt = 2131165350;
			
			// aapt resource value: 0x7F0700A7
			public const int take_ya_flp_txt1 = 2131165351;
			
			// aapt resource value: 0x7F0700A8
			public const int take_ya_pp_txt = 2131165352;
			
			// aapt resource value: 0x7F0700A9
			public const int take_ya_pp_txt1 = 2131165353;
			
			// aapt resource value: 0x7F0700AA
			public const int take_ya_pp_txt2 = 2131165354;
			
			// aapt resource value: 0x7F0700AB
			public const int take_ya_pp_txt3 = 2131165355;
			
			// aapt resource value: 0x7F0700AC
			public const int three_star_progress = 2131165356;
			
			// aapt resource value: 0x7F0700AD
			public const int title_text = 2131165357;
			
			// aapt resource value: 0x7F0700AF
			public const int totalfaresText = 2131165359;
			
			// aapt resource value: 0x7F0700AE
			public const int to_txt = 2131165358;
			
			// aapt resource value: 0x7F0700B0
			public const int tripButton = 2131165360;
			
			// aapt resource value: 0x7F0700B1
			public const int ts_temperature = 2131165361;
			
			// aapt resource value: 0x7F0700B2
			public const int two_star_progress = 2131165362;
			
			// aapt resource value: 0x7F0700B3
			public const int user_img = 2131165363;
			
			// aapt resource value: 0x7F0700B4
			public const int vehi_pics_cnt_btn = 2131165364;
			
			// aapt resource value: 0x7F0700B5
			public const int vehi_pics_intro_txt = 2131165365;
			
			// aapt resource value: 0x7F0700B6
			public const int vehi_pics_sub_txt = 2131165366;
			
			// aapt resource value: 0x7F0700B8
			public const int viewpager = 2131165368;
			
			// aapt resource value: 0x7F0700B7
			public const int view_ratings_details_btn = 2131165367;
			
			// aapt resource value: 0x7F0700B9
			public const int wanna_txt = 2131165369;
			
			// aapt resource value: 0x7F0700BA
			public const int wanna_txt2 = 2131165370;
			
			// aapt resource value: 0x7F0700BB
			public const int warning_frame = 2131165371;
			
			// aapt resource value: 0x7F0700BC
			public const int x = 2131165372;
			
			// aapt resource value: 0x7F0700BD
			public const int y = 2131165373;
			
			// aapt resource value: 0x7F0700BE
			public const int yearConstraint = 2131165374;
			
			// aapt resource value: 0x7F0700BF
			public const int year_ac_tv = 2131165375;
			
			// aapt resource value: 0x7F0700C0
			public const int year_lay = 2131165376;
			
			// aapt resource value: 0x7F0700C1
			public const int z = 2131165377;
			
			// aapt resource value: 0x7F0700C2
			public const int zoom_chip = 2131165378;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Integer
		{
			
			// aapt resource value: 0x7F080000
			public const int labels_animation_duration = 2131230720;
			
			static Integer()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Integer()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7F090000
			public const int account = 2131296256;
			
			// aapt resource value: 0x7F090001
			public const int activity_main = 2131296257;
			
			// aapt resource value: 0x7F090002
			public const int agreement_fragment = 2131296258;
			
			// aapt resource value: 0x7F090003
			public const int alert_dialog = 2131296259;
			
			// aapt resource value: 0x7F090004
			public const int appbar_main = 2131296260;
			
			// aapt resource value: 0x7F090005
			public const int collect_payment = 2131296261;
			
			// aapt resource value: 0x7F090006
			public const int container_main = 2131296262;
			
			// aapt resource value: 0x7F090007
			public const int driver_capture_layout = 2131296263;
			
			// aapt resource value: 0x7F090008
			public const int driver_onboarding = 2131296264;
			
			// aapt resource value: 0x7F090009
			public const int driver_partner_layout = 2131296265;
			
			// aapt resource value: 0x7F09000A
			public const int driver_signin_layout = 2131296266;
			
			// aapt resource value: 0x7F09000B
			public const int driver_signup_layout = 2131296267;
			
			// aapt resource value: 0x7F09000C
			public const int earnings = 2131296268;
			
			// aapt resource value: 0x7F09000D
			public const int home = 2131296269;
			
			// aapt resource value: 0x7F09000E
			public const int layout1 = 2131296270;
			
			// aapt resource value: 0x7F09000F
			public const int layout2 = 2131296271;
			
			// aapt resource value: 0x7F090010
			public const int licence_intro_layout = 2131296272;
			
			// aapt resource value: 0x7F090011
			public const int new_ride_request_overlay = 2131296273;
			
			// aapt resource value: 0x7F090012
			public const int offline_layout = 2131296274;
			
			// aapt resource value: 0x7F090014
			public const int partner_vehicle_fragment = 2131296276;
			
			// aapt resource value: 0x7F090013
			public const int partner_vehi_pics_fragment = 2131296275;
			
			// aapt resource value: 0x7F090015
			public const int pic_intro_layout = 2131296277;
			
			// aapt resource value: 0x7F090016
			public const int pic_preview_layout = 2131296278;
			
			// aapt resource value: 0x7F090017
			public const int progress = 2131296279;
			
			// aapt resource value: 0x7F090018
			public const int rating = 2131296280;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class Menu
		{
			
			// aapt resource value: 0x7F0A0000
			public const int bottomnav = 2131361792;
			
			// aapt resource value: 0x7F0A0001
			public const int menu_main = 2131361793;
			
			static Menu()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Menu()
			{
			}
		}
		
		public partial class Mipmap
		{
			
			// aapt resource value: 0x7F0B0000
			public const int ic_launcher = 2131427328;
			
			// aapt resource value: 0x7F0B0001
			public const int ic_launcher_foreground = 2131427329;
			
			// aapt resource value: 0x7F0B0002
			public const int ic_launcher_round = 2131427330;
			
			static Mipmap()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Mipmap()
			{
			}
		}
		
		public partial class Raw
		{
			
			// aapt resource value: 0x7F0C0000
			public const int alert = 2131492864;
			
			// aapt resource value: 0x7F0C0001
			public const int gray_mapstyle = 2131492865;
			
			static Raw()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Raw()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7F0D0001
			public const int action_settings = 2131558401;
			
			// aapt resource value: 0x7F0D0002
			public const int app_name = 2131558402;
			
			// aapt resource value: 0x7F0D0003
			public const int continue_txt = 2131558403;
			
			// aapt resource value: 0x7F0D0004
			public const int databaseUrl = 2131558404;
			
			// aapt resource value: 0x7F0D0005
			public const int default_progressbar = 2131558405;
			
			// aapt resource value: 0x7F0D0006
			public const int dialog_cancel = 2131558406;
			
			// aapt resource value: 0x7F0D0007
			public const int dialog_default_title = 2131558407;
			
			// aapt resource value: 0x7F0D0008
			public const int dialog_ok = 2131558408;
			
			// aapt resource value: 0x7F0D0009
			public const int driver_head_txt = 2131558409;
			
			// aapt resource value: 0x7F0D000A
			public const int driving_desc_txt = 2131558410;
			
			// aapt resource value: 0x7F0D000B
			public const int drv_partner_header = 2131558411;
			
			// aapt resource value: 0x7F0D000C
			public const int google_api_key = 2131558412;
			
			// aapt resource value: 0x7F0D0000
			public const int LOADING = 2131558400;
			
			// aapt resource value: 0x7F0D000D
			public const int partner_desc_txt = 2131558413;
			
			// aapt resource value: 0x7F0D000E
			public const int partner_head_txt = 2131558414;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7F0E0003
			public const int alert_dialog = 2131623939;
			
			// aapt resource value: 0x7F0E0000
			public const int AppTheme = 2131623936;
			
			// aapt resource value: 0x7F0E0001
			public const int AppTheme_DialogWhenLarge = 2131623937;
			
			// aapt resource value: 0x7F0E0002
			public const int AppTheme_MainScreen = 2131623938;
			
			// aapt resource value: 0x7F0E0004
			public const int dialog_blue_button = 2131623940;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
		
		public partial class Styleable
		{
			
			// aapt resource value: { 0x7F030000,0x7F030001,0x7F030002 }
			public static int[] CheckableCardView = new int[] {
					2130903040,
					2130903041,
					2130903042};
			
			// aapt resource value: 0
			public const int CheckableCardView_card_end_icon = 0;
			
			// aapt resource value: 1
			public const int CheckableCardView_card_text_body = 1;
			
			// aapt resource value: 2
			public const int CheckableCardView_card_text_head = 2;
			
			// aapt resource value: { 0x7F030004,0x7F030005,0x7F030006,0x7F030007,0x7F030008,0x7F030009,0x7F03000A,0x7F03000B,0x7F03000C,0x7F03000D }
			public static int[] ProgressWheel = new int[] {
					2130903044,
					2130903045,
					2130903046,
					2130903047,
					2130903048,
					2130903049,
					2130903050,
					2130903051,
					2130903052,
					2130903053};
			
			// aapt resource value: 0
			public const int ProgressWheel_matProg_barColor = 0;
			
			// aapt resource value: 1
			public const int ProgressWheel_matProg_barSpinCycleTime = 1;
			
			// aapt resource value: 2
			public const int ProgressWheel_matProg_barWidth = 2;
			
			// aapt resource value: 3
			public const int ProgressWheel_matProg_circleRadius = 3;
			
			// aapt resource value: 4
			public const int ProgressWheel_matProg_fillRadius = 4;
			
			// aapt resource value: 5
			public const int ProgressWheel_matProg_linearProgress = 5;
			
			// aapt resource value: 6
			public const int ProgressWheel_matProg_progressIndeterminate = 6;
			
			// aapt resource value: 7
			public const int ProgressWheel_matProg_rimColor = 7;
			
			// aapt resource value: 8
			public const int ProgressWheel_matProg_rimWidth = 8;
			
			// aapt resource value: 9
			public const int ProgressWheel_matProg_spinSpeed = 9;
			
			// aapt resource value: { 0x7F030003,0x7F03000E,0x7F03000F,0x7F030010,0x7F030011 }
			public static int[] Rotate3dAnimation = new int[] {
					2130903043,
					2130903054,
					2130903055,
					2130903056,
					2130903057};
			
			// aapt resource value: 0
			public const int Rotate3dAnimation_fromDeg = 0;
			
			// aapt resource value: 1
			public const int Rotate3dAnimation_pivotX = 1;
			
			// aapt resource value: 2
			public const int Rotate3dAnimation_pivotY = 2;
			
			// aapt resource value: 3
			public const int Rotate3dAnimation_rollType = 3;
			
			// aapt resource value: 4
			public const int Rotate3dAnimation_toDeg = 4;
			
			static Styleable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Styleable()
			{
			}
		}
		
		public partial class Xml
		{
			
			// aapt resource value: 0x7F100000
			public const int file_paths = 2131755008;
			
			static Xml()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Xml()
			{
			}
		}
	}
}
#pragma warning restore 1591
